version: "3.7"
services:
  flaskapi:
    image: webuko/api:snapshot
    ports:
      - 5000:5000

  mongodb:
    image: webuko/db:snapshot
    ports:
      - 27017:27017

  mongo_seed:
    image: webuko/db-seed:snapshot
    depends_on:
      - mongodb
    restart: on-failure

  tensorflow-serving:
    image: webuko/tf:snapshot
    command:
      - '--model_config_file=/models/model.config'
    ports:
      - 8501:8501
