version: "3.7"
services:
  tensorflow-serving:
    build: 
      context: ./tensorflow
      dockerfile: Dockerfile.tf
    command:
      - '--model_config_file=/models/model.config'
    ports: 
      - 8501:8501
    depends_on: 
      - flaskapi

  flaskapi:
    build:
      context: ./api
      dockerfile: Dockerfile.flask
    ports:
      - 5000:5000
    volumes:
      - ./api/code:/code

  mongodb:
    build:
      context: ./db
      dockerfile: .
    ports:
      - 27017:27017
    volumes:
      - ./db_data/:/data/db # to make db persistent
