swagger: '2.0'
info:
  description: 'This is the API documentation for the WeBuKo application.<br><br>All API methods can be called via `/api/method_name`. There is no authentication involved as all data and software in this project is open source. Data cannot be altered, only retrieved. API methods make use of the HTTP methods GET and POST. Where applicable, is specified below.'
  version: 1.0.0
  title: WeBuKo
host: "localhost:5000"
basePath: "/api"
tags:
  - name: allListings
    description: Retrieve all available listings.
  - name: filterListings
    description: Retrieve filtered listings.
  - name: pricePrediction
    description: Get a price prediction.
  - name: pricePredictionParamValues
    description: Get the required parameters for executing a price prediction.
  - name: avgPricePerNeighbourhood
    description: Get the average price per neighbourhood. Additionally, the geojson data for a neighbourhood is returned, as well.
schemes:
  - http
paths:
  /allListings:
    get:
      tags:
        - allListings
      summary: Get all listings with all available attributes.
      description: ''
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
    post:
      tags:
        - allListings
      summary: Get all listings with specific attributes only.
      description: ''
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Specification
          description: The specific values that are looked for in the requested listings.
          required: true
          schema:
            $ref: "#/definitions/ListingSpecification"
      responses:
        '200':
          description: Everything was okay.
        '400':
          description: Oops, something went wrong. Check the error message and make sure data is correctly submitted.
  /filterListings:
    post:
      tags:
        - filterListings
      summary: Filter the listings according to the provided inputs.
      description: The listings can be filtered according to the passed body as described below.
      produces:
        - application/json
      parameters:
        - in: body
          name: Filter
          description: The filter specification can contain any combination of the specified example arrays as seen below. Every entry in the request body is optional. Note that all numeric arrays in the request body must have exactly length **2**. The first position denotes the lower bound and the second position corresponds to the upper bound (both including).
          required: true
          schema:
            $ref: "#/definitions/FilterSpecification"
      responses:
        '200':
          description: Everything was okay.
        '400':
          description: Oops, something went wrong. Check the error message and make sure data is correctly submitted.
  /pricePrediction:
    post:
      tags:
        - pricePrediction
      summary: Gets a price estimation for a potential not yet listed AirBnB accommodation based on the specified characteristics.
      description: The specified fields are fed into a machine learning model that outputs an estimated price that could be offered when adding such an accommodation to AirBnB.
      produces:
        - application/json
      parameters:
        - in: body
          name: PredictionBody
          description: Parameters needed for making a price prediction
          required: true
          schema:
            $ref: "#/definitions/PredictionBody"
      responses:
        '200':
          description: Successful operation
  /pricePredictionParamValues:
    get:
      tags:
        - pricePredictionParamValues
      summary: Retrieve `pricePrediction` API request parameters.
      description: Retrieve valid values for the parameters of the `pricePrediction` API request.
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
  /avgPricePerNeighbourhood:
    get:
      tags:
        - avgPricePerNeighbourhood
      summary: Get average prices for all neighbourhoods without pre-filtering.
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
    post:
      tags:
        - avgPricePerNeighbourhood
      summary: Get average prices for all neighbourhoods with pre-filtering.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: Filter
          description: The filter specification can contain any combination of the specified example arrays as seen below. Every entry in the request body is optional. Note that all numeric arrays in the request body must have exactly length **2**. The first position denotes the lower bound and the second position corresponds to the upper bound (both including).
          schema:
            type: "object"
            properties:
              criteria:
                $ref: '#/definitions/filterCriteria'
      responses:
        '200':
          description: Everything was okay.
        '400':
          description: Oops, something went wrong. Check the error message and make sure data is correctly submitted.
definitions:
  ListingSpecification:
    type: "object"
    required:
      - fields
    properties:
      fields:
        $ref: '#/definitions/possibleReturnKeys' 
      force_fields:
        description: "Defines whether only listings should be retrieved that contain a non-empty value for all requested fields, as defined by the fields property."
        type: "boolean"
        example: true
    xml:
      name: "ListingSpecification"
  FilterSpecification:
    type: "object"
    required:
      - criteria
    properties:
      criteria:
        $ref: '#/definitions/filterCriteria'
      fields:
        $ref: '#/definitions/possibleReturnKeys' 
      force_fields:
        description: "Defines whether only listings should be retrieved that contain a non-empty value for all requested fields, as defined by the fields property."
        type: "boolean"
        example: false
  PredictionBody:
    type: "object"
    required:
       - price
       - bedrooms
       - bathrooms
       - accommodates
       - guests_included
       - gym
       - ac
       - elevator
       - neighbourhood
       - property_type
       - room_type
    properties:
      bathrooms:
        type: "integer"
        example: 1
      bedrooms:
        type: "integer"
        example: 3
      accommodates:
        type: "integer"
        example: 3
      guests_included:
        type: "integer"
        example: 6
      gym:
        type: "boolean"
        example: false
      ac:
        type: "boolean"
        example: true
      elevator:
        type: "boolean"
        example: true
      neighbourhood:
        type: "string"
        example: "Adlershof"
      property_type:
        type: "string"
        example: "House"
      room_type:
        type: "string"
        example: "Private room"
  possibleReturnKeys:
    type: "array"
    description: "Specifies which attributes for each listing should be retrieved."
    example: [description, price]
    items:
      type: "string"
      enum: ['id',
                 'listing_url',
                 'scrape_id',
                 'last_scraped',
                 'name',
                 'summary',
                 'space',
                 'description',
                 'experiences_offered',
                 'neighborhood_overview',
                 'notes',
                 'transit',
                 'access',
                 'interaction',
                 'house_rules',
                 'thumbnail_url',
                 'medium_url',
                 'picture_url',
                 'xl_picture_url',
                 'host_id',
                 'host_url',
                 'host_name',
                 'host_since',
                 'host_location',
                 'host_about',
                 'host_response_time',
                 'host_response_rate',
                 'host_acceptance_rate',
                 'host_is_superhost',
                 'host_thumbnail_url',
                 'host_picture_url',
                 'host_neighbourhood',
                 'host_listings_count',
                 'host_total_listings_count',
                 'host_verifications',
                 'host_has_profile_pic',
                 'host_identity_verified',
                 'street',
                 'neighbourhood',
                 'neighbourhood_cleansed',
                 'neighbourhood_group_cleansed',
                 'city',
                 'state',
                 'zipcode',
                 'market',
                 'smart_location',
                 'country_code',
                 'country',
                 'latitude',
                 'longitude',
                 'is_location_exact',
                 'property_type',
                 'room_type',
                 'accommodates',
                 'bathrooms',
                 'bedrooms',
                 'beds',
                 'bed_type',
                 'amenities',
                 'square_feet',
                 'price',
                 'weekly_price',
                 'monthly_price',
                 'security_deposit',
                 'cleaning_fee',
                 'guests_included',
                 'extra_people',
                 'minimum_nights',
                 'maximum_nights',
                 'minimum_minimum_nights',
                 'maximum_minimum_nights',
                 'minimum_maximum_nights',
                 'maximum_maximum_nights',
                 'minimum_nights_avg_ntm',
                 'maximum_nights_avg_ntm',
                 'calendar_updated',
                 'has_availability',
                 'availability_30',
                 'availability_60',
                 'availability_90',
                 'availability_365',
                 'calendar_last_scraped',
                 'number_of_reviews',
                 'number_of_reviews_ltm',
                 'first_review',
                 'last_review',
                 'review_scores_rating',
                 'review_scores_accuracy',
                 'review_scores_cleanliness',
                 'review_scores_checkin',
                 'review_scores_communication',
                 'review_scores_location',
                 'review_scores_value',
                 'requires_license',
                 'license',
                 'jurisdiction_names',
                 'instant_bookable',
                 'is_business_travel_ready',
                 'cancellation_policy',
                 'require_guest_profile_picture',
                 'require_guest_phone_verification',
                 'calculated_host_listings_count',
                 'calculated_host_listings_count_entire_homes',
                 'calculated_host_listings_count_private_rooms',
                 'calculated_host_listings_count_shared_rooms',
                 'reviews_per_month']
  filterCriteria:
    type: "object"
    properties:
      price:
        type: "array"
        items:
          type:
            "integer"
        example: [1, 100]
      bedrooms:
        type: "array"
        items:
          type:
            "integer"
        example: [1, 5]
      bathrooms:
        type: "array"
        items:
          type:
            "integer"
        example: [1, 5]
      accomodates:
        type: "array"
        items:
          type:
            "integer"
        example: [1, 5]
      property_type:
        type: "array"
        items:
          type:
            "string"
        example: [House, Apartment, Loft]
      room_type:
        type: "array"
        items:
          type:
            "string"
        example: [Entire home/apt, Private room]
      neighbourhood:
        type: "array"
        items:
          type:
            "string"
        example: [Adlershof]
    