FROM mongo:latest

COPY seed_data_1.json /seed_data_1.json
COPY seed_data_2.json /seed_data_2.json

# when in production --> use secrets
COPY import_data.sh /
ENTRYPOINT /import_data.sh airbnb airbnb-user pass