FROM mongo:4.4.6

COPY listings_seed_1.json /listings_seed_1.json
COPY listings_seed_2.json /listings_seed_2.json
COPY geo_seed.geojson /geo_seed.geojson

# when in production --> use secrets
COPY import_data.sh /
ENTRYPOINT /import_data.sh airbnb airbnb-user pass
