name: api-publish

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          file: ./api/Dockerfile.flask
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATIONNAME }}/api:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  db:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile.db
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATIONNAME }}/db:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  db-seed:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./db
          file: ./db/Dockerfile.seed
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATIONNAME }}/db-seed:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  tf:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./tensorflow
          file: ./tensorflow/Dockerfile.tf
          push: true
          tags: ${{ secrets.DOCKER_HUB_ORGANIZATIONNAME }}/tf:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
