name: ci-cd

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run tests and generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install flask
        pip install requests
        pip install sklearn==0.24.1
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        verbose: true
